#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellyfin"
name = "Jellyfin"
description.en = "Media System that manage and stream your media"
description.fr = "Système multimédia qui gère et diffuse vos médias"

version = "10.11.11~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-2.0-only"
website = "https://jellyfin.org"
demo = "https://demo.jellyfin.org/stable/web/index.html"
userdoc = "https://jellyfin.org/docs/"
code = "https://github.com/jellyfin/jellyfin"
cpe = "cpe:2.3:a:jellyfin:jellyfin"
fund = "https://opencollective.com/jellyfin"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = true

ldap = true

sso = true

disk = "300M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellyfin"

    [install.init_main_permission]
    help.en = "Jellyfin has its own login system, you should make it public to let external clients access it (mobile app, etc.)."
    help.fr = "Jellyfin a son propre système de connexion, vous devriez la laisser publique pour permettre la connexion de clients externes (app mobile, etc.)."
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Select an account to grant it access to Jellyfin's administration panel."
    ask.fr = "Choisissez un compte pour lui accorder l'accès au tableau de bord d'administration de Jellyfin."
    help.en = "You can grant this access to other accounts and groups with the permission system later."
    help.fr = "Vous pourrez octroire l'accès à d'autres comptes et groupes avec le système de permissions plus tard."
    type = "user"

[resources]

    [resources.sources.main]
    arm64.url = "https://repo.jellyfin.org/files/server/linux/stable/v10.11.11/arm64/jellyfin_10.11.11-arm64.tar.xz"
    arm64.sha256 = "2b0fa433548dbb81148218ea0cdf93f450d3db9049abf1e07c81bc5af9c79a92"
    amd64.url = "https://repo.jellyfin.org/files/server/linux/stable/v10.11.11/amd64/jellyfin_10.11.11-amd64.tar.xz"
    amd64.sha256 = "7e94666f5ffa08f3110eb3456e24210a720c9d7a04ebb0a23b775155451c1631"

    format = "tar.xz"
    extract = true
    in_subdir = true
    prefetch = false

    [resources.sources.main_archive]
    arm64.url = "https://repo.jellyfin.org/archive/server/linux/stable/v10.11.11/arm64/jellyfin_10.11.11-arm64.tar.xz"
    arm64.sha256 = "2b0fa433548dbb81148218ea0cdf93f450d3db9049abf1e07c81bc5af9c79a92"
    amd64.url = "https://repo.jellyfin.org/archive/server/linux/stable/v10.11.11/amd64/jellyfin_10.11.11-amd64.tar.xz"
    amd64.sha256 = "7e94666f5ffa08f3110eb3456e24210a720c9d7a04ebb0a23b775155451c1631"

    format = "tar.xz"
    extract = true
    in_subdir = true
    prefetch = false

    [resources.sources.ffmpeg]
    arm64.url = "https://repo.jellyfin.org/files/ffmpeg/linux/7.x/7.1.4-3/arm64/jellyfin-ffmpeg_7.1.4-3_portable_linuxarm64-gpl.tar.xz"
    arm64.sha256 = "77e4b5d044ab73e1f26c9aadaa5d6014d1782500bf2c29afb3ab81f5bea98b1f"
    amd64.url = "https://repo.jellyfin.org/files/ffmpeg/linux/7.x/7.1.4-3/amd64/jellyfin-ffmpeg_7.1.4-3_portable_linux64-gpl.tar.xz"
    amd64.sha256 = "cab9ff40a47e4232d231e4eb7e4e85fabfeec56c6905266bc94291fc0881f83f"

    format = "tar.xz"
    extract = true
    in_subdir = false

    [resources.sources.plugin_ldap]
    url = "https://repo.jellyfin.org/files/plugin/ldap-authentication/ldap-authentication_23.0.0.0.zip"
    sha256 = "952e33fa8d3ac512ccb5c1e2e1c655cbb1957e41fa1f00bd6ccf3076e0467446"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    # auth_header=false is because Jellyfin expects custom data in the Authorization HTTP header (notably, for Jellyfin Vue)
    main.url = "/"
    main.auth_header = false

    admin.protected = true
    admin.auth_header = false
    admin.show_tile = false

    [resources.ports]
    main.default = 8095
    # If one day we plan to declare them
    #servicediscovery.default = 1900
    #servicediscovery.exposed = "UDP"
    #servicediscovery.fixed = true
    #clientdiscovery.default = 7359
    #clientdiscovery.exposed = "UDP"
    #clientdiscovery.fixed = true

    [resources.apt]
    packages = [
        "sqlite3" # temporarily needed to tweak db during upgrade script to 10.11.5
    ]
